- name: Install base packages
  apt: pkg={{ item }} state=present update-cache=yes cache_valid_time=86400
  with_items:
  - python-pip
  - python-dev
  - python-imaging
  - virtualenvwrapper
  - gettext
  - python-numpy
  - git
  - opensp
  - tidy
  - libmalaga7
  - python-psycopg2
  - language-pack-fi
  - python-software-properties
  - libxslt1-dev
  - libavcodec-dev
  - libavformat-dev
  - libswscale-dev
  - libxml2-dev
  - zlib1g-dev
  - default-jdk
  - libvoikko1
  - unzip
